
// 列表
export const SAMPLING_LIST_START = 'SAMPLING_LIST_START'
export const SAMPLING_LIST_SUCCESS = 'SAMPLING_LIST_SUCCESS'
// 加载列表rows和rowKeys
export const SAMPLING_LIST_KEY = 'SAMPLING_LIST_KEY'
// 表格点击项
export const SAMPLING_LIST_CLICK = 'SAMPLING_LIST_CLICK'

// 新增 / 编辑
export const SAMPLING_ITEM_ADD = 'SAMPLING_ITEM_ADD'
export const SAMPLING_ITEM_EDIT = 'SAMPLING_ITEM_EDIT'
export const SAMPLING_ITEM_SAVE = 'SAMPLING_ITEM_SAVE'
export const SAMPLING_ITEM_SAVE_SUCCESS = 'SAMPLING_ITEM_SAVE_SUCCESS'

// 激活 / 禁用
export const ACTIVE_SAMPLING_START = 'ACTIVE_SAMPLING_START'
export const ACTIVE_SAMPLING_SUCCESS = 'ACTIVE_SAMPLING_SUCCESS'

export const UNACTIVE_SAMPLING_START = 'UNACTIVE_SAMPLING_START'
export const UNACTIVE_SAMPLING_SUCCESS = 'UNACTIVE_SAMPLING_SUCCESS'

// 取消弹框操作
export const CANCEL_SAMPLING = 'CANCEL_SAMPLING'
