
// 搜索search
export const MARKREPORT_SEARCH_START = 'MARKREPORT_SEARCH_START'
export const MARKREPORT_SEARCH_SUCCESS = 'MARKREPORT_SEARCH_SUCCESS'

// search 下面的报告模板列表
// 样品
export const MARKREPORT_SAMPLE_START = 'MARKREPORT_SAMPLE_START'
export const MARKREPORT_SAMPLE_SUCCESS = 'MARKREPORT_SAMPLE_SUCCESS'

// 加载列表rows和rowKeys
export const MARKREPORT_LIST_KEY = 'MARKREPORT_LIST_KEY'

// 新增 / 编辑
export const MARKREPORT_ITEM_ADD = 'MARKREPORT_ITEM_ADD'
export const MARKREPORT_ITEM_EDIT = 'MARKREPORT_ITEM_EDIT'
export const MARKREPORT_ITEM_SAVE = 'MARKREPORT_ITEM_SAVE'
export const MARKREPORT_ITEM_SAVE_SUCCESS = 'MARKREPORT_ITEM_SAVE_SUCCESS'

// 激活 / 禁用
export const ACTIVE_MARKREPORT_START = 'ACTIVE_MARKREPORT_START'
export const ACTIVE_MARKREPORT_SUCCESS = 'ACTIVE_MARKREPORT_SUCCESS'
export const UNACTIVE_MARKREPORT_SUCCESS = 'UNACTIVE_MARKREPORT_SUCCESS'

// 报告模板列表数据
export const MARKREPORT_REPORTTEMPLATE_START = 'MARKREPORT_REPORTTEMPLATE_START'
export const MARKREPORT_REPORTTEMPLATE_SUCCESS = 'MARKREPORT_REPORTTEMPLATE_SUCCESS'
//获取报告模板的rowsKey
export const ROWS_MARKREPORT_TEMPLATE = 'ROWS_MARKREPORT_TEMPLATE'

// 获取签章列表数据
export const MARKREPORT_SIGNATURE_START = 'MARKREPORT_SIGNATURE_START'
export const MARKREPORT_SIGNATURE_SUCCESS = 'MARKREPORT_SIGNATURE_SUCCESS'
// 获取签章的rowsKey
export const ROWS_MARKREPORT_QUALIFICATION = 'ROWS_MARKREPORT_QUALIFICATION'

// 编制报告 按钮
export const MARKREPORT_BTN_START = 'MARKREPORT_BTN_START'
export const MARKREPORT_BTN_SUCCESS = 'MARKREPORT_BTN_SUCCESS'
// 编制报告 列表
export const MARKREPORT_BTN_LIST_START = 'MARKREPORT_BTN_LIST_START'
export const MARKREPORT_BTN_LIST_SUCCESS = 'MARKREPORT_BTN_LIST_SUCCESS'

// 报告作废 按钮
export const MARKREPORT_VOID_BTN_START = 'MARKREPORT_VOID_BTN_START'
export const MARKREPORT_VOID_BTN_SUCCESS = 'MARKREPORT_VOID_BTN_SUCCESS'
// 列表rows
export const MARKREPORT_TABLE_ROWS = 'MARKREPORT_TABLE_ROWS'

// 删除报告
export const DELETE_MARKREPORT_START = 'DELETE_MARKREPORT_START'
export const DELETE_MARKREPORT_SUCCESS = 'DELETE_MARKREPORT_SUCCESS'

// 编制完成
export const DONE_MARKREPORT_START = 'DONE_MARKREPORT_START'
export const DONE_MARKREPORT_SUCCESS = 'DONE_MARKREPORT_SUCCESS'


// 取消弹框操作
export const CANCEL_MARKREPORT = 'CANCEL_MARKREPORT'
