
// 搜索search
export const REPORTSENT_SEARCH_START = 'REPORTSENT_SEARCH_START'
export const REPORTSENT_SEARCH_SUCCESS = 'REPORTSENT_SEARCH_SUCCESS'

// search 下面的报告模板列表
// 样品
export const REPORTSENT_SAMPLE_START = 'REPORTSENT_SAMPLE_START'
export const REPORTSENT_SAMPLE_SUCCESS = 'REPORTSENT_SAMPLE_SUCCESS'

// 加载报告列表rows和rowKeys
export const REPORTSENT_TABLE_ROWS = 'REPORTSENT_TABLE_ROWS'
// 报告的列表点击项
export const REPORTSENT_TABLE_SELECT = 'REPORTSENT_TABLE_SELECT'
// 交付方式
export const REPORTSENT_METHODLIST = 'REPORTSENT_METHODLIST'
// 交付物
export const REPORTSENT_GOODSLIST = 'REPORTSENT_GOODSLIST'

// 交付报告
export const DELIVERY_REPORTSENT = 'DELIVERY_REPORTSENT'
export const DELIVERY_REPORTSENT_START = 'DELIVERY_REPORTSENT_START'
export const DELIVERY_REPORTSENT_VERIFY = 'DELIVERY_REPORTSENT_VERIFY'
export const DELIVERY_REPORTSENT_SUCCESS = 'DELIVERY_REPORTSENT_SUCCESS'

// 审核记录
export const REPORTSENT_APPROVE = 'REPORTSENT_APPROVE'

// 交付记录列表
export const DELIVERY_RECORD_LIST = 'DELIVERY_RECORD_LIST'
export const DELIVERY_RECORD_LIST_SUCCESS = 'DELIVERY_RECORD_LIST_SUCCESS'
// 交付记录 列表rows
export const REPORTSENT_DELIVERY_ROWS = 'REPORTSENT_DELIVERY_ROWS'

// 取消交付
export const UNDELIVERY_REPORTSENT = 'UNDELIVERY_REPORTSENT'
export const UNDELIVERY_REPORTSENT_START = 'UNDELIVERY_REPORTSENT_START'
export const UNDELIVERY_REPORTSENT_VERIFY = 'UNDELIVERY_REPORTSENT_VERIFY'
export const UNDELIVERY_REPORTSENT_SUCCESS = 'UNDELIVERY_REPORTSENT_SUCCESS'

// 取消弹框操作
export const CANCEL_REPORTSENT = 'CANCEL_REPORTSENT'
