// 列表树
export const LOAD_LOCATION_START = 'LOAD_LOCATION_START'
export const LOAD_LOCATION_SUCCESS = 'LOAD_LOCATION_SUCCESS'
// 获取可搜索树选中节点
export const LOCATION_ITEM_SELECT = 'LOCATION_ITEM_SELECT'

export const LOCATION_LIST_ROWS = 'LOCATION_LIST_ROWS'
// 新增
export const LOCATION_ADD = 'LOCATION_ADD'
export const LOCATION_EDIT = 'LOCATION_EDIT'
export const LOCATION_ADD_START = 'LOCATION_ADD_START'
export const LOCATION_ADD_SUCCESS = 'LOCATION_ADD_SUCCESS'
// 新增 左侧列表树
export const LOCATION_ADD_LOAD = 'LOCATION_ADD_LOAD'
export const LOCATION_ADD_LOAD_SUCCESS = 'LOCATION_ADD_LOAD_SUCCESS'

// 删除
export const DELETE_LOCATION_START = 'DELETE_LOCATION_START'
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS'

// 取消弹框操作
export const CANCEL_LOCATION = 'CANCEL_LOCATION'
