
// 搜索search
export const REPORTARCHIVED_FILTER_START = 'REPORTARCHIVED_FILTER_START'
export const REPORTARCHIVED_FILTER_SUCCESS = 'REPORTARCHIVED_FILTER_SUCCESS'

// 加载列表rows和rowKeys
export const REPORTARCHIVED_TABLE_ROWS = 'REPORTARCHIVED_TABLE_ROWS'
export const REPORTARCHIVED_TABLE_SELECT = 'REPORTARCHIVED_TABLE_SELECT'

// 扫描 报告编号
export const REPORTARCHIVED_NUMBER_START = 'REPORTARCHIVED_NUMBER_START'
export const REPORTARCHIVED_NUMBER_SUCCESS = 'REPORTARCHIVED_NUMBER_SUCCESS'

// 交付报告
export const REPORT_REPORTARCHIVED = 'REPORT_REPORTARCHIVED'
export const REPORT_REPORTARCHIVED_START = 'REPORT_REPORTARCHIVED_START'
export const REPORT_REPORTARCHIVED_SUCCESS = 'REPORT_REPORTARCHIVED_SUCCESS'

// 取消弹框操作
export const CANCEL_REPORTARCHIVED = 'CANCEL_REPORTARCHIVED'
