

// 搜索search
export const REPORTTEMPLATE_SEARCH_START = 'REPORTTEMPLATE_SEARCH_START'
export const REPORTTEMPLATE_SEARCH_SUCCESS = 'REPORTTEMPLATE_SEARCH_SUCCESS'
// search 下面的报告模板列表
export const REPORTTEMPLATE_START = 'REPORTTEMPLATE_START'
export const REPORTTEMPLATE_SUCCESS = 'REPORTTEMPLATE_SUCCESS'
// 加载列表rows和rowKeys
export const REPORTTEMPLATE_LIST_KEY = 'REPORTTEMPLATE_LIST_KEY'
// 表格点击项
export const REPORTTEMPLATE_LIST_CLICK = 'REPORTTEMPLATE_LIST_CLICK'

// 新增 / 编辑
export const REPORTTEMPLATE_ITEM_ADD = 'REPORTTEMPLATE_ITEM_ADD'
export const REPORTTEMPLATE_ITEM_EDIT = 'REPORTTEMPLATE_ITEM_EDIT'
export const REPORTTEMPLATE_ITEM_SAVE = 'REPORTTEMPLATE_ITEM_SAVE'
export const REPORTTEMPLATE_ITEM_SAVE_SUCCESS = 'REPORTTEMPLATE_ITEM_SAVE_SUCCESS'
// 删除检验资质
export const DELETE_REPORTTEMPLATE_START = 'DELETE_REPORTTEMPLATE_START'
export const DELETE_REPORTTEMPLATE_SUCCESS = 'DELETE_REPORTTEMPLATE_SUCCESS'

// 上传文件确认
export const UPLOAD_REPORTTEMPLATE_START = 'UPLOAD_REPORTTEMPLATE_START'
export const UPLOAD_REPORTTEMPLATE_SUCCESS = 'UPLOAD_REPORTTEMPLATE_SUCCESS'
// 上传文件列表
export const UPLOAD_REPORTTEMPLATE_LIST_START = 'UPLOAD_REPORTTEMPLATE_LIST_START'
export const UPLOAD_REPORTTEMPLATE_LIST_SUCCESS = 'UPLOAD_REPORTTEMPLATE_LIST_SUCCESS'
// 删除上传文件
export const UPLOAD_REPORTTEMPLATE_DELETE_START = 'UPLOAD_REPORTTEMPLATE_DELETE_START'
export const UPLOAD_REPORTTEMPLATE_DELETE_SUCCESS = 'UPLOAD_REPORTTEMPLATE_DELETE_SUCCESS'
// 上传文件勾选想
export const UPLOAD_REPORTTEMPLATE_ROWS = 'UPLOAD_REPORTTEMPLATE_ROWS'

// 激活 / 禁用
export const ACTIVE_REPORTTEMPLATE_START = 'ACTIVE_REPORTTEMPLATE_START'
export const ACTIVE_REPORTTEMPLATE_SUCCESS = 'ACTIVE_REPORTTEMPLATE_SUCCESS'
export const UNACTIVE_REPORTTEMPLATE_SUCCESS = 'UNACTIVE_REPORTTEMPLATE_SUCCESS'

// 设置主文件
export const MAIN_FILE_REPORTTEMPLATE_START = 'MAIN_FILE_REPORTTEMPLATE_START'
export const MAIN_FILE_REPORTTEMPLATE_SUCCESS = 'MAIN_FILE_REPORTTEMPLATE_SUCCESS'

// 取消弹框操作
export const CANCEL_REPORTTEMPLATE = 'CANCEL_REPORTTEMPLATE'

// 上传弹框
export const UPLOAD_MODAL_REPORTTEMPLATE = 'UPLOAD_MODAL_REPORTTEMPLATE'
