

// 暂存资质认证搜索抬头
export const TEMPORARY_DEPOSIT_QUALIFICATION_TITLE_START = 'TEMPORARY_DEPOSIT_QUALIFICATION_TITLE_START'
export const TEMPORARY_DEPOSIT_QUALIFICATION_TITLE_SUCCESS = 'TEMPORARY_DEPOSIT_QUALIFICATION_TITLE_SUCCESS'
// 资质首页加载存储rows和rowKeys
export const QUALIFICATION_LIST_KEY = 'QUALIFICATION_LIST_KEY'
export const QUALIFICATION_LIST_CLICK = 'QUALIFICATION_LIST_CLICK'
// 新增检验资质
export const ADD_QUALIFICATION = 'ADD_QUALIFICATION'
export const ADD_QUALIFICATION_START = 'ADD_QUALIFICATION_START'
export const ADD_QUALIFICATION_SUCCESS = 'ADD_QUALIFICATION_SUCCESS'
// 新增资质时暂存资质搜索抬头
export const ADD_QUALIFICATION_TITLE_START = 'ADD_QUALIFICATION_TITLE_START'
export const ADD_QUALIFICATION_TITLE_SUCCESS = 'ADD_QUALIFICATION_TITLE_SUCCESS'
// 新增资质时加载存储rows和rowKeys
export const ADD_QUALIFICATION_KEY = 'ADD_QUALIFICATION_KEY'
// 编辑检验资质
export const EDIT_QUALIFICATION = 'EDIT_QUALIFICATION'
export const EDIT_QUALIFICATION_START = 'EDIT_QUALIFICATION_START'
export const EDIT_QUALIFICATION_SUCCESS = 'EDIT_QUALIFICATION_SUCCESS'
// 删除检验资质
export const DELETE_QUALIFICATION_START = 'DELETE_QUALIFICATION_START'
export const DELETE_QUALIFICATION_SUCCESS = 'DELETE_QUALIFICATION_SUCCESS'
// 激活检验资质
export const ACTIVE_QUALIFICATION_START = 'ACTIVE_QUALIFICATION_START'
export const ACTIVE_QUALIFICATION_SUCCESS = 'ACTIVE_QUALIFICATION_SUCCESS'
// 禁用检验资质
export const UNACTIVE_QUALIFICATION_START = 'UNACTIVE_QUALIFICATION_START'
export const UNACTIVE_QUALIFICATION_SUCCESS = 'UNACTIVE_QUALIFICATION_SUCCESS'
// 关联产品搜索加列表
export const CONNECT_PRODUCT_QUALIFICATION_TITLE_START = 'CONNECT_PRODUCT_QUALIFICATION_TITLE_START'
export const CONNECT_PRODUCT_QUALIFICATION_TITLE_SUCCESS = 'CONNECT_PRODUCT_QUALIFICATION_TITLE_SUCCESS'
// 关联产品
export const CONNECT_PRODUCT_QUALIFICATION = 'CONNECT_PRODUCT_QUALIFICATION'
export const CONNECT_PRODUCT_QUALIFICATION_START = 'CONNECT_PRODUCT_QUALIFICATION_START'
export const CONNECT_PRODUCT_QUALIFICATION_SUCCESS = 'CONNECT_PRODUCT_QUALIFICATION_SUCCESS'
// 关联产品时加载存储rows和rowKeys
export const CONNECT_QUALIFICATION_KEY = 'CONNECT_QUALIFICATION_KEY'

// 取消弹框操作
export const CANCEL_QUALIFICATION = 'CANCEL_QUALIFICATION'
