
// 右侧列表
export const DEPTTASKSCOPE_LIST_START = 'DEPTTASKSCOPE_LIST_START'
export const DEPTTASKSCOPE_LIST_SUCCESS = 'DEPTTASKSCOPE_LIST_SUCCESS'
export const DEPTTASKSCOPE_LIST_ROWS = 'DEPTTASKSCOPE_LIST_ROWS'
// 新增
export const DEPTTASKSCOPE_ADD = 'DEPTTASKSCOPE_ADD'
export const DEPTTASKSCOPE_ADD_START = 'DEPTTASKSCOPE_ADD_START'
export const DEPTTASKSCOPE_ADD_SUCCESS = 'DEPTTASKSCOPE_ADD_SUCCESS'
// 新增 左侧列表树
export const DEPTTASKSCOPE_ADD_LOAD = 'DEPTTASKSCOPE_ADD_LOAD'
export const DEPTTASKSCOPE_ADD_LOAD_SUCCESS = 'DEPTTASKSCOPE_ADD_LOAD_SUCCESS'
// 获取可搜索树选中的节点
// export const DEPTTASKSCOPE_ADD_SELECT = 'DEPTTASKSCOPE_ADD_SELECT'
// 新增 右侧列表
export const DEPTTASKSCOPE_LIST_ADD_START = 'DEPTTASKSCOPE_LIST_ADD_START'
export const DEPTTASKSCOPE_LIST_ADD_SUCCESS = 'DEPTTASKSCOPE_LIST_ADD_SUCCESS'
export const DEPTTASKSCOPE_LIST_ADD_ROW = 'DEPTTASKSCOPE_LIST_ADD_ROW'

// 删除
export const DELETE_DEPTTASKSCOPE_START = 'DELETE_DEPTTASKSCOPE_START'
export const DELETE_DEPTTASKSCOPE_SUCCESS = 'DELETE_DEPTTASKSCOPE_SUCCESS'

// 取消弹框操作
export const CANCEL_DEPTTASKSCOPE = 'CANCEL_DEPTTASKSCOPE'
